// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → links*
 */
export interface FooterDocumentDataLinksItem {
  /**
   * link text field in *Footer → links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * link url field in *Footer → links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Footer → contact*
 */
export interface FooterDocumentDataContactItem {
  /**
   * link text field in *Footer → contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * link url field in *Footer → contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterDocumentDataLinksItem>>;

  /**
   * contact field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact: prismic.GroupField<Simplify<FooterDocumentDataContactItem>>;

  /**
   * copyright field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | ImageTextRightSlice
  | ImageTextLeftSlice
  | FaqsSlice
  | DirectorsSectionSlice
  | MemorabiliaSlice
  | AboutSectionSlice
  | HomePageHeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type LegalServicesDocumentDataSlicesSlice =
  | ServicesSectionSlice
  | AboutSectionSlice
  | LegalHeroSlice
  | LegalProcessSlice;

/**
 * Content for Legal Services documents
 */
interface LegalServicesDocumentData {
  /**
   * Slice Zone field in *Legal Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LegalServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Legal Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legal_services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Legal Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legal_services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Legal Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keywords field in *Legal Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_services.keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;
}

/**
 * Legal Services document from Prismic
 *
 * - **API ID**: `legal_services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LegalServicesDocumentData>,
    "legal_services",
    Lang
  >;

type ScholarshipDocumentDataSlicesSlice = FormSlice;

/**
 * Content for Scholarship documents
 */
interface ScholarshipDocumentData {
  /**
   * Slice Zone field in *Scholarship*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: scholarship.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ScholarshipDocumentDataSlicesSlice> /**
   * Meta Title field in *Scholarship*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: scholarship.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Scholarship*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: scholarship.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Scholarship*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: scholarship.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Keywords field in *Scholarship*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scholarship.keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;
}

/**
 * Scholarship document from Prismic
 *
 * - **API ID**: `scholarship`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ScholarshipDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ScholarshipDocumentData>,
    "scholarship",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomeDocument
  | LegalServicesDocument
  | ScholarshipDocument;

/**
 * Item in *AboutSection → Default → Primary → carousel*
 */
export interface AboutSectionSliceDefaultPrimaryCarouselItem {
  /**
   * image field in *AboutSection → Default → Primary → carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * image title field in *AboutSection → Default → Primary → carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.carousel[].image_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_title: prismic.KeyTextField;

  /**
   * content field in *AboutSection → Default → Primary → carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.carousel[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * title field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * carousel field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<AboutSectionSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Item in *DirectorsSection → Default → Primary → directors*
 */
export interface DirectorsSectionSliceDefaultPrimaryDirectorsItem {
  /**
   * image field in *DirectorsSection → Default → Primary → directors*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: directors_section.default.primary.directors[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *DirectorsSection → Default → Primary → directors*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: directors_section.default.primary.directors[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * name field in *DirectorsSection → Default → Primary → directors*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: directors_section.default.primary.directors[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *DirectorsSection → Default → Primary*
 */
export interface DirectorsSectionSliceDefaultPrimary {
  /**
   * title field in *DirectorsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: directors_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *DirectorsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: directors_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * directors field in *DirectorsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: directors_section.default.primary.directors[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  directors: prismic.GroupField<
    Simplify<DirectorsSectionSliceDefaultPrimaryDirectorsItem>
  >;
}

/**
 * Default variation for DirectorsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DirectorsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DirectorsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DirectorsSection*
 */
type DirectorsSectionSliceVariation = DirectorsSectionSliceDefault;

/**
 * DirectorsSection Shared Slice
 *
 * - **API ID**: `directors_section`
 * - **Description**: DirectorsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DirectorsSectionSlice = prismic.SharedSlice<
  "directors_section",
  DirectorsSectionSliceVariation
>;

/**
 * Item in *Faqs → Default → Primary → faqs*
 */
export interface FaqsSliceDefaultPrimaryFaqsItem {
  /**
   * title field in *Faqs → Default → Primary → faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *Faqs → Default → Primary → faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * title field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * content field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * faqs field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * title field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Item in *HomePageHero → Default → Primary → carousel*
 */
export interface HomePageHeroSliceDefaultPrimaryCarouselItem {
  /**
   * service name field in *HomePageHero → Default → Primary → carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.carousel[].service_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_name: prismic.KeyTextField;

  /**
   * image field in *HomePageHero → Default → Primary → carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HomePageHero → Default → Primary*
 */
export interface HomePageHeroSliceDefaultPrimary {
  /**
   * title field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * carousel field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<HomePageHeroSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for HomePageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomePageHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomePageHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomePageHero*
 */
type HomePageHeroSliceVariation = HomePageHeroSliceDefault;

/**
 * HomePageHero Shared Slice
 *
 * - **API ID**: `home_page_hero`
 * - **Description**: HomePageHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomePageHeroSlice = prismic.SharedSlice<
  "home_page_hero",
  HomePageHeroSliceVariation
>;

/**
 * Primary content in *ImageTextLeft → Default → Primary*
 */
export interface ImageTextLeftSliceDefaultPrimary {
  /**
   * title field in *ImageTextLeft → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_left.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * heading field in *ImageTextLeft → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_left.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *ImageTextLeft → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_left.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * image field in *ImageTextLeft → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_left.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *ImageTextLeft → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_left.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * link text field in *ImageTextLeft → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_left.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Default variation for ImageTextLeft Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextLeftSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextLeftSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageTextLeft*
 */
type ImageTextLeftSliceVariation = ImageTextLeftSliceDefault;

/**
 * ImageTextLeft Shared Slice
 *
 * - **API ID**: `image_text_left`
 * - **Description**: ImageTextLeft
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextLeftSlice = prismic.SharedSlice<
  "image_text_left",
  ImageTextLeftSliceVariation
>;

/**
 * Primary content in *ImageTextRight → Default → Primary*
 */
export interface ImageTextRightSliceDefaultPrimary {
  /**
   * image field in *ImageTextRight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_right.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *ImageTextRight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_right.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * heading field in *ImageTextRight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_right.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *ImageTextRight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_right.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * link field in *ImageTextRight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_right.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * link text field in *ImageTextRight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_right.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Default variation for ImageTextRight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextRightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextRightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageTextRight*
 */
type ImageTextRightSliceVariation = ImageTextRightSliceDefault;

/**
 * ImageTextRight Shared Slice
 *
 * - **API ID**: `image_text_right`
 * - **Description**: ImageTextRight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextRightSlice = prismic.SharedSlice<
  "image_text_right",
  ImageTextRightSliceVariation
>;

/**
 * Primary content in *LegalHero → Default → Primary*
 */
export interface LegalHeroSliceDefaultPrimary {
  /**
   * image field in *LegalHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *LegalHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *LegalHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for LegalHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LegalHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LegalHero*
 */
type LegalHeroSliceVariation = LegalHeroSliceDefault;

/**
 * LegalHero Shared Slice
 *
 * - **API ID**: `legal_hero`
 * - **Description**: LegalHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalHeroSlice = prismic.SharedSlice<
  "legal_hero",
  LegalHeroSliceVariation
>;

/**
 * Item in *LegalProcess → Default → Primary → process*
 */
export interface LegalProcessSliceDefaultPrimaryProcessItem {
  /**
   * number field in *LegalProcess → Default → Primary → process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_process.default.primary.process[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * title field in *LegalProcess → Default → Primary → process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_process.default.primary.process[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *LegalProcess → Default → Primary → process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_process.default.primary.process[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *LegalProcess → Default → Primary*
 */
export interface LegalProcessSliceDefaultPrimary {
  /**
   * title field in *LegalProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_process.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *LegalProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_process.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * process field in *LegalProcess → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_process.default.primary.process[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  process: prismic.GroupField<
    Simplify<LegalProcessSliceDefaultPrimaryProcessItem>
  >;

  /**
   * image field in *LegalProcess → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_process.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for LegalProcess Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LegalProcessSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LegalProcess*
 */
type LegalProcessSliceVariation = LegalProcessSliceDefault;

/**
 * LegalProcess Shared Slice
 *
 * - **API ID**: `legal_process`
 * - **Description**: LegalProcess
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalProcessSlice = prismic.SharedSlice<
  "legal_process",
  LegalProcessSliceVariation
>;

/**
 * Primary content in *Memorabilia → Default → Primary*
 */
export interface MemorabiliaSliceDefaultPrimary {
  /**
   * title field in *Memorabilia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: memorabilia.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *Memorabilia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: memorabilia.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * subtitle1 field in *Memorabilia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: memorabilia.default.primary.subtitle1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle1: prismic.KeyTextField;

  /**
   * biography field in *Memorabilia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: memorabilia.default.primary.biography
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  biography: prismic.KeyTextField;

  /**
   * subtitle2 field in *Memorabilia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: memorabilia.default.primary.subtitle2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle2: prismic.KeyTextField;

  /**
   * life of service field in *Memorabilia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: memorabilia.default.primary.life_of_service
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  life_of_service: prismic.KeyTextField;
}

/**
 * Default variation for Memorabilia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemorabiliaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MemorabiliaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Memorabilia*
 */
type MemorabiliaSliceVariation = MemorabiliaSliceDefault;

/**
 * Memorabilia Shared Slice
 *
 * - **API ID**: `memorabilia`
 * - **Description**: Memorabilia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemorabiliaSlice = prismic.SharedSlice<
  "memorabilia",
  MemorabiliaSliceVariation
>;

/**
 * Item in *ServicesSection → Default → Primary → service*
 */
export interface ServicesSectionSliceDefaultPrimaryServiceItem {
  /**
   * title field in *ServicesSection → Default → Primary → service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.service[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *ServicesSection → Default → Primary → service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.service[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *ServicesSection → Default → Primary*
 */
export interface ServicesSectionSliceDefaultPrimary {
  /**
   * title field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * heading field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * service field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.service[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  service: prismic.GroupField<
    Simplify<ServicesSectionSliceDefaultPrimaryServiceItem>
  >;
}

/**
 * Default variation for ServicesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesSection*
 */
type ServicesSectionSliceVariation = ServicesSectionSliceDefault;

/**
 * ServicesSection Shared Slice
 *
 * - **API ID**: `services_section`
 * - **Description**: ServicesSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSectionSlice = prismic.SharedSlice<
  "services_section",
  ServicesSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinksItem,
      FooterDocumentDataContactItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LegalServicesDocument,
      LegalServicesDocumentData,
      LegalServicesDocumentDataSlicesSlice,
      ScholarshipDocument,
      ScholarshipDocumentData,
      ScholarshipDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimaryCarouselItem,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      DirectorsSectionSlice,
      DirectorsSectionSliceDefaultPrimaryDirectorsItem,
      DirectorsSectionSliceDefaultPrimary,
      DirectorsSectionSliceVariation,
      DirectorsSectionSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryFaqsItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceVariation,
      FormSliceDefault,
      HomePageHeroSlice,
      HomePageHeroSliceDefaultPrimaryCarouselItem,
      HomePageHeroSliceDefaultPrimary,
      HomePageHeroSliceVariation,
      HomePageHeroSliceDefault,
      ImageTextLeftSlice,
      ImageTextLeftSliceDefaultPrimary,
      ImageTextLeftSliceVariation,
      ImageTextLeftSliceDefault,
      ImageTextRightSlice,
      ImageTextRightSliceDefaultPrimary,
      ImageTextRightSliceVariation,
      ImageTextRightSliceDefault,
      LegalHeroSlice,
      LegalHeroSliceDefaultPrimary,
      LegalHeroSliceVariation,
      LegalHeroSliceDefault,
      LegalProcessSlice,
      LegalProcessSliceDefaultPrimaryProcessItem,
      LegalProcessSliceDefaultPrimary,
      LegalProcessSliceVariation,
      LegalProcessSliceDefault,
      MemorabiliaSlice,
      MemorabiliaSliceDefaultPrimary,
      MemorabiliaSliceVariation,
      MemorabiliaSliceDefault,
      ServicesSectionSlice,
      ServicesSectionSliceDefaultPrimaryServiceItem,
      ServicesSectionSliceDefaultPrimary,
      ServicesSectionSliceVariation,
      ServicesSectionSliceDefault,
    };
  }
}
