// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_image_text: dynamic(() => import("./AboutImageText")),
  about_section: dynamic(() => import("./AboutSection")),
  about_text_image: dynamic(() => import("./AboutTextImage")),
  card_block: dynamic(() => import("./CardBlock")),
  directors_section: dynamic(() => import("./DirectorsSection")),
  faqs: dynamic(() => import("./Faqs")),
  form: dynamic(() => import("./Form")),
  home_page_hero: dynamic(() => import("./HomePageHero")),
  image_text_left: dynamic(() => import("./ImageTextLeft")),
  image_text_right: dynamic(() => import("./ImageTextRight")),
  legal_hero: dynamic(() => import("./LegalHero")),
  legal_process: dynamic(() => import("./LegalProcess")),
  memorabilia: dynamic(() => import("./Memorabilia")),
  services_section: dynamic(() => import("./ServicesSection")),
};
