// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  directors_section: dynamic(() => import("./DirectorsSection")),
  faqs: dynamic(() => import("./Faqs")),
  form: dynamic(() => import("./Form")),
  home_page_hero: dynamic(() => import("./HomePageHero")),
  memorabilia: dynamic(() => import("./Memorabilia")),
};
