import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Caveat } from "next/font/google";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

const caveat = Caveat({
  variable: "--font-caveat",
  display: "swap",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Modupe Sapential Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${caveat.variable} antialiased`}
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen overflow-x-hidden m-0 p-0 flex flex-col bg-white text-black`}
          suppressHydrationWarning={true}
        >
          <Navbar />
          <main className="flex-grow-[1]">{children}</main>
          <Footer />
        </body>
      </body>
    </html>
  );
}
