import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

const caros = localFont({
  src: [
    {
      path: "../public/fonts/cretype-Caros-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/cretype-Caros-ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/cretype-Caros-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/cretype-Caros-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/cretype-Caros.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-caros",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Modupe Sapential Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${caros.variable} antialiased`}>
        <body
          className={`${caros.variable} antialiased min-h-screen overflow-x-hidden m-0 p-0 flex flex-col bg-white text-black`}
          suppressHydrationWarning={true}
        >
          <Navbar />
          <main className="flex-grow-[1]">{children}</main>
          <Footer />
        </body>
      </body>
    </html>
  );
}
